/** Stable id aligned with `image_with_text_overlay_7JgREg` in `diabetes-care.html`. */
export const IMAGE_TEXT_OVERLAY_SECTION_ID =
  'shopify-section-template--26520397447459__image_with_text_overlay_7JgREg';

export const IMAGE_TEXT_OVERLAY_VARS = `#${IMAGE_TEXT_OVERLAY_SECTION_ID}{--section-padding-top:0px;--section-padding-bottom:0px;--color-foreground:255 255 255;--color-border:var(--color-foreground)/0.1;--color-border-dark:var(--color-foreground)/0.4;--color-border-light:var(--color-foreground)/0.06;--color-highlight:224 165 128;--color-button-background:255 255 255;--color-button-border:255 255 255;--color-button-text:23 23 23;--color-overlay:23 23 23;--overlay-opacity:0.7}`;

/**
 * Banner overlay: image fills the frame; text sits on top (not stacked below).
 * Overrides global `mobile:media--auto` rules that put `.banner__media` in document flow.
 */
export const IMAGE_TEXT_OVERLAY_BANNER_CSS =
  `@media screen and (max-width:767px){#${IMAGE_TEXT_OVERLAY_SECTION_ID} .dciw-banner{position:relative;overflow:hidden;width:100%;aspect-ratio:4/5;min-height:min(75vw,420px);height:auto!important}#${IMAGE_TEXT_OVERLAY_SECTION_ID} .dciw-banner .banner__media{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;min-height:0!important;aspect-ratio:unset!important}#${IMAGE_TEXT_OVERLAY_SECTION_ID} .dciw-banner .banner__media .media,#${IMAGE_TEXT_OVERLAY_SECTION_ID} .dciw-banner .banner__media picture{position:absolute!important;inset:0!important;height:100%!important;width:100%!important}#${IMAGE_TEXT_OVERLAY_SECTION_ID} .dciw-banner .banner__media img{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;object-fit:cover!important;aspect-ratio:unset!important}#${IMAGE_TEXT_OVERLAY_SECTION_ID} .dciw-banner .banner__overlay{position:absolute!important;inset:0!important;width:100%!important;height:100%!important}#${IMAGE_TEXT_OVERLAY_SECTION_ID} .dciw-banner .banner__content{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;overflow:hidden}}` +
  `@media screen and (min-width:768px){#${IMAGE_TEXT_OVERLAY_SECTION_ID} .dciw-banner{position:relative;overflow:hidden}#${IMAGE_TEXT_OVERLAY_SECTION_ID} .dciw-banner .banner__media{position:absolute;inset:0;width:100%;height:100%}#${IMAGE_TEXT_OVERLAY_SECTION_ID} .dciw-banner .banner__media .media,#${IMAGE_TEXT_OVERLAY_SECTION_ID} .dciw-banner .banner__media picture{height:100%;width:100%}#${IMAGE_TEXT_OVERLAY_SECTION_ID} .dciw-banner .banner__media img{height:100%;width:100%;object-fit:cover}#${IMAGE_TEXT_OVERLAY_SECTION_ID} .dciw-banner .banner__overlay{position:absolute;inset:0}#${IMAGE_TEXT_OVERLAY_SECTION_ID} .dciw-banner .banner__content{position:absolute;inset:0;width:100%;height:100%}}`;
